name: Machina Templates Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: feed-git
          SLACK_USERNAME: GitHub Actions
        with:
          text: "A new pull request has been opened: <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}> by <https://github.com/${{ github.actor }}|${{ github.actor }}>.\n\n**Title:** ${{ github.event.pull_request.title }}\n**Branch:** ${{ github.event.pull_request.head.ref }}\n**Link to PR:** ${{ github.event.pull_request.html_url }}"
